/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SiteImport } from './routes/_site'
import { Route as AuthImport } from './routes/_auth'
import { Route as SiteIndexImport } from './routes/_site/index'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as SiteLessonsIndexImport } from './routes/_site/lessons/index'
import { Route as SiteLessonsGameImport } from './routes/_site/lessons/_game'
import { Route as SiteLessonsGameLessonIndexImport } from './routes/_site/lessons/_game/$lesson/index'
import { Route as SiteLessonsGameLessonPlayImport } from './routes/_site/lessons/_game/$lesson/play'

// Create Virtual Routes

const SiteLessonsImport = createFileRoute('/_site/lessons')()

// Create/Update Routes

const SiteRoute = SiteImport.update({
  id: '/_site',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const SiteLessonsRoute = SiteLessonsImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => SiteRoute,
} as any)

const SiteIndexRoute = SiteIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const SiteLessonsIndexRoute = SiteLessonsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteLessonsRoute,
} as any)

const SiteLessonsGameRoute = SiteLessonsGameImport.update({
  id: '/_game',
  getParentRoute: () => SiteLessonsRoute,
} as any)

const SiteLessonsGameLessonIndexRoute = SiteLessonsGameLessonIndexImport.update(
  {
    id: '/$lesson/',
    path: '/$lesson/',
    getParentRoute: () => SiteLessonsGameRoute,
  } as any,
)

const SiteLessonsGameLessonPlayRoute = SiteLessonsGameLessonPlayImport.update({
  id: '/$lesson/play',
  path: '/$lesson/play',
  getParentRoute: () => SiteLessonsGameRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SiteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexImport
      parentRoute: typeof SiteImport
    }
    '/_site/lessons': {
      id: '/_site/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof SiteLessonsImport
      parentRoute: typeof SiteImport
    }
    '/_site/lessons/_game': {
      id: '/_site/lessons/_game'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof SiteLessonsGameImport
      parentRoute: typeof SiteLessonsRoute
    }
    '/_site/lessons/': {
      id: '/_site/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof SiteLessonsIndexImport
      parentRoute: typeof SiteLessonsImport
    }
    '/_site/lessons/_game/$lesson/play': {
      id: '/_site/lessons/_game/$lesson/play'
      path: '/$lesson/play'
      fullPath: '/lessons/$lesson/play'
      preLoaderRoute: typeof SiteLessonsGameLessonPlayImport
      parentRoute: typeof SiteLessonsGameImport
    }
    '/_site/lessons/_game/$lesson/': {
      id: '/_site/lessons/_game/$lesson/'
      path: '/$lesson'
      fullPath: '/lessons/$lesson'
      preLoaderRoute: typeof SiteLessonsGameLessonIndexImport
      parentRoute: typeof SiteLessonsGameImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SiteLessonsGameRouteChildren {
  SiteLessonsGameLessonPlayRoute: typeof SiteLessonsGameLessonPlayRoute
  SiteLessonsGameLessonIndexRoute: typeof SiteLessonsGameLessonIndexRoute
}

const SiteLessonsGameRouteChildren: SiteLessonsGameRouteChildren = {
  SiteLessonsGameLessonPlayRoute: SiteLessonsGameLessonPlayRoute,
  SiteLessonsGameLessonIndexRoute: SiteLessonsGameLessonIndexRoute,
}

const SiteLessonsGameRouteWithChildren = SiteLessonsGameRoute._addFileChildren(
  SiteLessonsGameRouteChildren,
)

interface SiteLessonsRouteChildren {
  SiteLessonsGameRoute: typeof SiteLessonsGameRouteWithChildren
  SiteLessonsIndexRoute: typeof SiteLessonsIndexRoute
}

const SiteLessonsRouteChildren: SiteLessonsRouteChildren = {
  SiteLessonsGameRoute: SiteLessonsGameRouteWithChildren,
  SiteLessonsIndexRoute: SiteLessonsIndexRoute,
}

const SiteLessonsRouteWithChildren = SiteLessonsRoute._addFileChildren(
  SiteLessonsRouteChildren,
)

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteLessonsRoute: typeof SiteLessonsRouteWithChildren
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteLessonsRoute: SiteLessonsRouteWithChildren,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof SiteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof SiteIndexRoute
  '/lessons': typeof SiteLessonsGameRouteWithChildren
  '/lessons/': typeof SiteLessonsIndexRoute
  '/lessons/$lesson/play': typeof SiteLessonsGameLessonPlayRoute
  '/lessons/$lesson': typeof SiteLessonsGameLessonIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof SiteIndexRoute
  '/lessons': typeof SiteLessonsIndexRoute
  '/lessons/$lesson/play': typeof SiteLessonsGameLessonPlayRoute
  '/lessons/$lesson': typeof SiteLessonsGameLessonIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/lessons': typeof SiteLessonsRouteWithChildren
  '/_site/lessons/_game': typeof SiteLessonsGameRouteWithChildren
  '/_site/lessons/': typeof SiteLessonsIndexRoute
  '/_site/lessons/_game/$lesson/play': typeof SiteLessonsGameLessonPlayRoute
  '/_site/lessons/_game/$lesson/': typeof SiteLessonsGameLessonIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/lessons'
    | '/lessons/'
    | '/lessons/$lesson/play'
    | '/lessons/$lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/lessons'
    | '/lessons/$lesson/play'
    | '/lessons/$lesson'
  id:
    | '__root__'
    | '/_auth'
    | '/_site'
    | '/_auth/login'
    | '/_auth/register'
    | '/_site/'
    | '/_site/lessons'
    | '/_site/lessons/_game'
    | '/_site/lessons/'
    | '/_site/lessons/_game/$lesson/play'
    | '/_site/lessons/_game/$lesson/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_site"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/register"
      ]
    },
    "/_site": {
      "filePath": "_site.tsx",
      "children": [
        "/_site/",
        "/_site/lessons"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_site/": {
      "filePath": "_site/index.tsx",
      "parent": "/_site"
    },
    "/_site/lessons": {
      "filePath": "_site/lessons",
      "parent": "/_site",
      "children": [
        "/_site/lessons/_game",
        "/_site/lessons/"
      ]
    },
    "/_site/lessons/_game": {
      "filePath": "_site/lessons/_game.tsx",
      "parent": "/_site/lessons",
      "children": [
        "/_site/lessons/_game/$lesson/play",
        "/_site/lessons/_game/$lesson/"
      ]
    },
    "/_site/lessons/": {
      "filePath": "_site/lessons/index.tsx",
      "parent": "/_site/lessons"
    },
    "/_site/lessons/_game/$lesson/play": {
      "filePath": "_site/lessons/_game/$lesson/play.tsx",
      "parent": "/_site/lessons/_game"
    },
    "/_site/lessons/_game/$lesson/": {
      "filePath": "_site/lessons/_game/$lesson/index.tsx",
      "parent": "/_site/lessons/_game"
    }
  }
}
ROUTE_MANIFEST_END */
